import React from 'react';
import { User, LogOut, Plus, Users } from 'lucide-react';

export default function LobbyScreen({
  playerName,
  teamName,
  setTeamName,
  teamCodeInput,
  setTeamCodeInput,
  errorMsg,
  handleCreateTeamSubmit,
  handleJoinTeamSubmit,
  handleContinueSolo,
  handleDisconnect
}) {
  return (
    <div className="flex-1 flex flex-col justify-center items-center p-4 min-h-[500px]">
      <div className="w-full max-w-xl bg-cyber-card border border-cyber-cyan/50 p-8 rounded shadow-neon-cyan space-y-6 relative">
        <div className="absolute top-0 left-0 w-full h-1 bg-cyber-cyan shadow-neon-cyan"></div>

        <div className="flex justify-between items-center border-b border-cyber-cyan/25 pb-4">
          <div className="text-left font-mono">
            <p className="text-[10px] text-cyber-gray">OPERATOR ASSIGNED</p>
            <h2 className="text-lg font-bold text-cyber-cyan flex items-center">
              <User className="w-4 h-4 mr-1.5" /> {playerName.toUpperCase()}
            </h2>
          </div>
          <button
            onClick={handleDisconnect}
            className="text-cyber-gray hover:text-cyber-red font-mono text-xs flex items-center space-x-1"
          >
            <LogOut className="w-3.5 h-3.5" />
            <span>LOG OUT</span>
          </button>
        </div>

        {errorMsg && (
          <div className="text-cyber-red text-center font-mono text-xs bg-cyber-red-dark/30 border border-cyber-red/30 p-2 rounded">
            {errorMsg}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 font-mono">
          {/* Option A: Create a Team */}
          <div className="p-5 border border-cyber-cyan/30 bg-cyber-bg/40 rounded flex flex-col justify-between space-y-4 hover:border-cyber-cyan transition shadow-md">
            <div>
              <h3 className="text-sm font-bold text-cyber-cyan flex items-center">
                <Plus className="w-4 h-4 mr-1" /> HOST SECURE SQUAD
              </h3>
              <p className="text-[11px] text-cyber-gray mt-2 leading-relaxed">
                Create a new protected room code. Invite up to 2 other operatives to join you in solving levels together in real-time.
              </p>
            </div>

            <form onSubmit={handleCreateTeamSubmit} className="space-y-3">
              <input
                type="text"
                required
                placeholder="Enter team name"
                value={teamName}
                onChange={(e) => setTeamName(e.target.value)}
                maxLength={16}
                className="w-full bg-cyber-bg text-cyber-cyan border border-cyber-cyan/30 focus:border-cyber-cyan p-2 text-xs rounded outline-none placeholder-cyber-cyan/20"
              />
              <button
                type="submit"
                className="w-full bg-cyber-cyan text-black font-bold p-2 text-xs hover:bg-white hover:text-black rounded transition duration-200 border border-cyber-cyan"
              >
                HOST TEAM
              </button>
            </form>
          </div>

          {/* Option B: Join Existing Team */}
          <div className="p-5 border border-cyber-cyan/30 bg-cyber-bg/40 rounded flex flex-col justify-between space-y-4 hover:border-cyber-cyan transition shadow-md">
            <div>
              <h3 className="text-sm font-bold text-cyber-cyan flex items-center">
                <Users className="w-4 h-4 mr-1" /> SECURE LINK TO SQUAD
              </h3>
              <p className="text-[11px] text-cyber-gray mt-2 leading-relaxed">
                Enter the 6-digit access code generated by your squad leader. Work together to crack nodes.
              </p>
            </div>

            <form onSubmit={handleJoinTeamSubmit} className="space-y-3">
              <input
                type="text"
                required
                placeholder="Enter 6-digit code"
                value={teamCodeInput}
                onChange={(e) => setTeamCodeInput(e.target.value)}
                maxLength={8}
                className="w-full bg-cyber-bg text-cyber-cyan border border-cyber-cyan/30 focus:border-cyber-cyan p-2 text-xs rounded text-center tracking-widest outline-none placeholder-cyber-cyan/20"
              />
              <button
                type="submit"
                className="w-full bg-cyber-cyan/20 text-cyber-cyan hover:bg-cyber-cyan hover:text-black font-bold p-2 text-xs rounded transition duration-200 border border-cyber-cyan/50"
              >
                VALIDATE NODE
              </button>
            </form>
          </div>
        </div>

        <div className="border-t border-cyber-cyan/10 pt-4 flex flex-col items-center">
          <p className="text-[10px] text-cyber-gray font-mono mb-2">OR PROCEED WITHOUT A TEAM LOBBY</p>
          <button
            onClick={handleContinueSolo}
            className="px-6 py-2 bg-cyber-blue/20 hover:bg-cyber-blue hover:text-black text-cyber-blue border border-cyber-blue/40 text-xs font-mono font-bold rounded transition shadow-[0_0_8px_rgba(0,102,255,0.15)]"
          >
            PLAY SOLO (CONTINUE WITHOUT TEAM)
          </button>
        </div>
      </div>
    </div>
  );
}
